name: Deploy SQS

on:
  push:
    branches: [ feature/sqs-construct ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Use Node
        uses: actions/setup-node@v2

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node.js
        run: |
          sudo npm install -g npm@latest
          sudo npm install package.json

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Synth
        run: |
          cdk synth
      